version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      dynamodb-local:
        condition: service_healthy
    environment:
      REGION: us-east-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000
      TABLE_NAME: Customers
    networks:
      - app-network

  dynamodb-local:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "8000:8000"
    volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  dynamodb-data:


networks:
  app-network:
    driver: bridge